version: '2'
services:
  ipsec_vpn_server:
    image: "hwdsl2/ipsec-vpn-server"
    environment:
      - VPN_IPSEC_PSK=${VPN_IPSEC_PSK}
      - VPN_USER=${VPN_USER}
      - VPN_PASSWORD=${VPN_PASSWORD}
    ports:
        - "500:500/udp"
        - "4500:4500/udp"
    volumes:
        - /lib/modules:/lib/modules:ro
    restart: always
    privileged: true

